name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,4,9 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: freeze
      run: |
        pip freeze > requirements.txt
        cat requirements.txt
        cat ./login/sha1.py
      
    - name: Pip
      run: |
        pip3 install requests pycryptodome
         
    - name: HealthyCheckIn
      run: |
        python3 17wanxiao.py <<EOF
        ${{secrets.USERNAME}}
        ${{secrets.PASSWORD}}
        ${{secrets.SCKEY}}
        EOF
        
